name: Swift

on:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild test -workspace thereto-ios/thereto-ios.xcworkspace -scheme thereto-ios -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=13.6'
